-- Generated by nwg-displays on 2026-08-05 at 00:50:10. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "6714x1399",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@143.93",
    position = "4154x752",
    scale = 1.0
})
