#!/usr/bin/env python3

import argparse
import json
import math
import re
import subprocess
import os
import stat
import tempfile
from pathlib import Path


REQUIRE_LINE = 'require("hyprland/shellOverrides/appOpacity")'


def lua_quote(value: str) -> str:
    return '"' + (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    ) + '"'


def get_hyprland_clients():
    try:
        result = subprocess.run(
            ["hyprctl", "clients", "-j"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True,
        )
        clients = json.loads(result.stdout)
        if isinstance(clients, list):
            return clients
    except Exception as exc:
        print(f"Warning: could not read Hyprland clients: {exc}")

    return []


def normalize(value: str) -> str:
    return str(value or "").strip().lower()


def clamp_opacity(value, default):
    try:
        value = float(value)
    except (TypeError, ValueError):
        return default

    if not math.isfinite(value):
        return default

    return max(0.10, min(1.00, value))


def resolve_real_class(match: str, rule_id: str, clients):
    target = normalize(match)
    rule_id_normalized = normalize(rule_id)
    classes = []

    for client in clients:
        cls = str(client.get("initialClass") or "").strip()
        if cls and cls not in classes:
            classes.append(cls)

    for cls in classes:
        if normalize(cls) == target:
            return cls

    for cls in classes:
        if normalize(cls) == rule_id_normalized:
            return cls

    for cls in classes:
        n = normalize(cls)

        if n.endswith("." + target):
            return cls

        if target.endswith("." + n):
            return cls

    def compact(value):
        return re.sub(r"[^a-z0-9]", "", normalize(value))

    compact_target = compact(target)

    if compact_target:
        for cls in classes:
            if compact(cls) == compact_target:
                return cls

    return match


def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists() and path.read_text() == content:
        return False

    existing_mode = (
        stat.S_IMODE(path.stat().st_mode)
        if path.exists()
        else 0o644
    )

    fd, temp_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        text=True,
    )

    try:
        with os.fdopen(fd, "w") as temp_file:
            temp_file.write(content)
            temp_file.flush()
            os.fsync(temp_file.fileno())

        os.chmod(temp_name, existing_mode)
        os.replace(temp_name, path)
        return True
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass


def ensure_require(main_path: Path):
    try:
        content = main_path.read_text()
    except FileNotFoundError:
        content = ""

    lines = content.splitlines()

    if any(line.strip() == REQUIRE_LINE for line in lines):
        return

    if content and not content.endswith("\n"):
        content += "\n"

    content += REQUIRE_LINE + "\n"

    return write_text(main_path, content)


def build_application_opacity(config_path: Path, output_path: Path):
    try:
        data = json.loads(config_path.read_text())
    except Exception as exc:
        print(f"Could not read {config_path}: {exc}")
        return None

    decoration = (
        data.get("hyprland", {})
        .get("decoration", {})
    )

    rules = decoration.get("applicationOpacityRules", [])

    inactive = clamp_opacity(
        decoration.get("inactiveOpacity", 0.9),
        0.9,
    )

    if not isinstance(rules, list):
        rules = []

    clients = get_hyprland_clients()

    lines = [
        "-- AUTO-GENERATED by end4-pC Application Opacity.",
        "-- Do not edit this file manually.",
        "",
    ]

    for rule in rules:
        if not isinstance(rule, dict):
            continue

        if not bool(rule.get("enabled", False)):
            continue

        rule_id = str(rule.get("id", "")).strip()
        saved_match = str(rule.get("match", "")).strip()

        if not rule_id and not saved_match:
            continue

        real_class = resolve_real_class(
            saved_match,
            rule_id,
            clients,
        )

        if not real_class:
            continue

        active = clamp_opacity(
            rule.get("active", 1.0),
            1.0,
        )

        safe_id = re.sub(
            r"[^A-Za-z0-9_-]",
            "_",
            rule_id or real_class,
        )

        matcher = "^" + re.escape(real_class) + "$"

        lines.append(
            "hl.window_rule({"
            f" name = {lua_quote('end4-app-opacity-' + safe_id)},"
            f" match = {{ initial_class = {lua_quote(matcher)} }},"
            f" opacity = "
            f"{lua_quote(f'{active:.2f} override {inactive:.2f} override')}"
            " })"
        )

    return write_text(
        output_path,
        "\n".join(lines) + "\n",
    )

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--config",
        required=True,
        type=Path,
    )

    parser.add_argument(
        "--output",
        required=True,
        type=Path,
    )

    parser.add_argument(
        "--main",
        required=True,
        type=Path,
    )

    args = parser.parse_args()

    output_changed = build_application_opacity(
        args.config,
        args.output,
    )

    if output_changed is None:
        return 1

    require_changed = ensure_require(args.main)

    if not output_changed and not require_changed:
        return 0

    try:
        result = subprocess.run(
            ["hyprctl", "reload"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        print("Could not reload Hyprland: hyprctl was not found in PATH")
        return 1

    if result.returncode != 0:
        print(
            result.stderr.strip()
            or result.stdout.strip()
        )
        return result.returncode

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
